#include <stdio.h>
#include <stdlib.h>

/**
 * main - The sequence of triangle numbers is generated by adding the natural
 *  numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 *  The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *  Let us list the factors of the first seven triangle numbers:
 *   1: 1
 *   3: 1,3
 *   6: 1,2,3,6
 *  10: 1,2,5,10
 *  15: 1,3,5,15
 *  21: 1,3,7,21
 *  28: 1,2,4,7,14,28
 *  We can see that 28 is the first triangle number to have over five divisors.
 *  What is the value of the first triangle number to have over five hundred divisors?
 * Return: 0 if success, 1 if fail
 */
int main(void)
{
	long factory = 1, count = 0, mul, n_start = 5, end_n = 500, progress_n, lap;

	/*triangel num = n * (n + 1) / 2, I'm giving a head start of n = 5*/
	/*factor center pair = median and end, or less median and end + 1*/
	mul = n_start * (n_start + 1) / 2;
	lap = end_n / 10, progress_n = lap; /*progress monitoring*/
	while (count < end_n / 2)
	{
		factory = 1, count = 0;
		while (mul / factory > factory)
		{
			if (mul % factory == 0)
				count++;
			factory++;
		}
		if (count < end_n / 2)
			n_start++, mul += n_start;
		if (count > progress_n) /*progress monitoring*/
			printf("pass %ld factors\n", progress_n * 2), progress_n += lap;
	}
	printf("Final ans: %ld\n", mul);
	return (0);
}
